name: First workflow
on: workflow_dispatch
jobs: 
  firts-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello world"
      - name: print goodbye
        run: | 
          echo "good bye"
          echo "sam"
